# Workflow based on https://github.com/joncloud/makensis-action-test/blob/publish/.github/workflows/main.yml

name: SlimeVR Windows Web Installer

on: [ push, pull_request, workflow_dispatch ]

env:
  JRE_VERSION: "17.0.11+9"
  SERVER_VERSION: "19.0.0"

jobs:
  download:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - name: Download assets
        shell: powershell
        run: |
          $JRE_VERSION = "${{ env.JRE_VERSION }}"
          $assetsDir = "windows/web/assets"
          New-Item -ItemType Directory -Force -Path $assetsDir
          # VC++
          Invoke-WebRequest -Uri "https://aka.ms/vc14/vc_redist.x64.exe" -OutFile "$assetsDir/vc_redist.x64.exe"
          # JRE
          Invoke-WebRequest -Uri "https://github.com/adoptium/temurin17-binaries/releases/download/$JRE_VERSION/OpenJDK17U-jre_x64_windows_hotspot_${JRE_VERSION//+/}_10.zip" -OutFile "$assetsDir/jre.zip"
          # Server
          Invoke-WebRequest -Uri "https://github.com/SlimeVR/SlimeVR-Server/releases/latest/download/SlimeVR-win64.zip" -OutFile "$assetsDir/SlimeVR-Server-latest.zip"
          # Driver
          Invoke-WebRequest -Uri "https://github.com/SlimeVR/SlimeVR-OpenVR-Driver/releases/latest/download/slimevr-openvr-driver-win64.zip" -OutFile "$assetsDir/slimevr-openvr-driver-win64.zip"
          # Feeder
          Invoke-WebRequest -Uri "https://github.com/SlimeVR/SlimeVR-Feeder-App/releases/latest/download/SlimeVR-Feeder-App-win64.zip" -OutFile "$assetsDir/SlimeVR-Feeder-App-latest.zip"
      - uses: actions/upload-artifact@v6
        with:
          name: web-assets
          path: windows/web/assets

  build:
    needs: download
    runs-on: windows-2022

    env:
      # The directory of the web installer project
      WINDOWS_WEB_DIR: ${{ github.workspace }}/windows/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Download assets
        uses: actions/download-artifact@v6
        with:
          name: web-assets
          path: ${{ env.WINDOWS_WEB_DIR }}/assets
      - name: Update NSI defines
        shell: powershell
        run: |
          $JRE_VERSION = "${{ env.JRE_VERSION }}"
          $SERVER_VERSION = "${{ env.SERVER_VERSION }}"
          $content = Get-Content -Path "${{ env.WINDOWS_WEB_DIR }}/slimevr_web_installer.nsi" -Raw
          $content = $content -replace '!define JREVersion "PLACEHOLDER_VERSION"', "!define JREVersion `"${JRE_VERSION}`""
          $content = $content -replace 'OutFile "slimevr_${$SERVER_VERSION}_offline_installer\.exe"', "OutFile `"${OUTFILE_NAME}`""
          Set-Content -Path "${{ env.WINDOWS_WEB_DIR }}/slimevr_web_installer.nsi" -Value $content -NoNewline

      - name: Create NSIS installer
        uses: joncloud/makensis-action@v5.0
        with:
          script-file: ${{ env.WINDOWS_WEB_DIR }}/slimevr_web_installer.nsi

      - name: Upload the installer as a build artifact
        uses: actions/upload-artifact@v6
        with:
          # Artifact name
          name: "slimevr_web_installer" # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.WINDOWS_WEB_DIR }}/slimevr_web_installer.exe

      - name: Upload to draft release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          files: "${{ env.WINDOWS_WEB_DIR }}/slimevr_web_installer.exe"
